config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  devise_for :users
  root 'rooms#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user

  has_attached_file :avatar
  has_attached_file :image1
  has_attached_file :image2
  has_attached_file :image3
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :image1, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :image2, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :image3, content_type: /\Aimage\/.*\z/

  validates :accommodates, :numericality => { greater_than: 0}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, :lastname, presence: true

  has_many :rooms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  use_growlyflash 
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
   devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname])

 end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id if current_user
    @booking.approved = false
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:room_id, :user_id, :startdate, :enddate, :guestcount, :approved)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @booking = Booking.new()
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id if current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :accommodates, :bathroom, :price, :kitchen, :internet, :pets, :user_id, :avatar, :image1, :image2, :image3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <input type="date" class="datepicker">
    <%= f.label :startdate %>
    <%= f.date_select :startdate %>
  </input>

  <input type="date" class="datepicker">
    <%= f.label :enddate %>
    <%= f.date_select :enddate %>
  </input>

  <div class="input-field">
    <%= f.label :guestcount %>
    <%= f.number_field :guestcount %>
  </div>

  <%= r = @room.id  %>
  <% f.hidden_field :room_id, :value => r %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>User</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Guestcount</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.room %></td>
        <td><%= booking.user %></td>
        <td><%= booking.startdate %></td>
        <td><%= booking.enddate %></td>
        <td><%= booking.guestcount %></td>
        <td><%= booking.approved %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @booking.room %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @booking.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @booking.enddate %>
</p>

<p>
  <strong>Guestcount:</strong>
  <%= @booking.guestcount %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @booking.approved %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnB</title>
    <%= csrf_meta_tags %>
    <%= growlyflash_static_notices %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<h5>Lets blow some shit up</h5>

app/views/partials/_nav.html.erb
<nav>
    <div class="nav-wrapper">
      <div class="tnt-logo"></div>
      <a href="/" class="brand-logo">AirTnT - Explosive Accomodation</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
        <%= link_to "New Room", new_room_path %>
      </li>
        <!-- LOGIN/LOGOUT BUTTON -->
       <% if user_signed_in? %>
         <li>
         <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
         </li>
       <% else %>
         <li>
         <%= link_to('Login', new_user_session_path)  %>
         </li>
       <% end %>
       <!-- REGISTER/EDIT REGISTRATION BUTTON -->
       <% if user_signed_in? %>
         <li>
         <%= link_to('Edit registration', edit_user_registration_path) %>
         </li>
       <% else %>
         <li>
         <%= link_to('Register', new_user_registration_path)  %>
         </li>
       <% end %>
      </ul>
    </div>
  </nav>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "validate" %>
  </div>

  <div class="input-field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "validate" %>
  </div>

  <div class="input-field">
    <%= f.label :accommodates %>
    <%= f.number_field :accommodates, class: "validate", min: 0  %>
  </div>

  <div class="input-field">
    <%= f.label :bathroom %>
    <%= f.number_field :bathroom, class: "validate", min: 0 %>
  </div>

  <div class="input-field">
    <%= f.label :price %>
    <%= f.text_field :price, class: "validate", min: 0  %>
  </div>

  <div class="all-checker">

    <input  type="checkbox" id="1" />
      <label class="checker" for="1">
        <%= f.label :kitchen %>
        <%= f.check_box :kitchen %>
      </label>

  <input  type="checkbox" id="2" />
    <label class="checker" for="2">
    <%= f.label :internet %>
    <%= f.check_box :internet %>
  </label>

<input type="checkbox" id="3" />
  <label class="checker" for="3">
    <%= f.label :pets %>
    <%= f.check_box :pets %>
  </label>
</div>


<div>
  <%= f.file_field :avatar %>
  <%= f.file_field :image1 %>
  <%= f.file_field :image2 %>
  <%= f.file_field :image3 %>

</div>


  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>




    <% @rooms.each do |room| %>
      <div class="room-container">
        <div class="r-name">
        <%= room.name %>
        <div class="r-image">
            <%= image_tag room.avatar, style: "width: 100%; height: auto; padding: 5px;" %>       
           </div>
      </div>

      <div class="r-left">
      <div class="r-user">
        <h5>Details</h5>

      </div>
      <div class="r-details">
        <div class="r-desc">
        <p>Owned By: <%= room.user.firstname %></p>
          <%= room.description %>
        </div>
        <div class="r-bools">
        <div class="r-bools-left">
        Accomodates: <%= room.accommodates %>
        Bathrooms: <%= room.bathroom %>
        </div>
        <div class="r-bools-right">
        Kitchen: <%= room.kitchen %>
        Wifi<%= room.internet %>
        Pets allowed: <%= room.pets %>
      </div>
      </div>
        <div class="r-price"><%= room.price %></div>
      </div>


      </div>
    </div>

      <%= link_to 'Show', room %>
      <%= link_to 'Edit', edit_room_path(room) %>
      <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>


<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<div class="shroom-container">
  <div class="r-name">
  <%= @room.name %>
  <div class="r-image">
      <%= image_tag @room.avatar, style: "width: 100%; height: auto; padding: 5px;" %>
     </div>
     <div class="r-bools">
     <div class="r-bools-left">
     <p>Accomodates: <%= @room.accommodates %></p>
     <p>Bathrooms: <%= @room.bathroom %></p>
     </div>
     <div class="r-bools-right">
     <p>Kitchen: <%= @room.kitchen %></p>
     <p>Wifi: <%= @room.internet %></p>
     <p>Pets allowed: <%= @room.pets %></p>
   </div>
   <div class="r-price">$<%= @room.price %> a night</div>
   </div>
</div>

<div class="shr-left">
<div class="r-user">
  <h5>Details</h5>

</div>
<div class="r-details">
  <div class="shr-desc">
  <p>Owned By: <%= @room.user.firstname %></p>
    <%= @room.description %>
  </div>
  <div class="r_photos">
    <%= image_tag @room.avatar, style: "width: 150px; height: auto; padding: 5px; float: left;" %>
    <%= image_tag @room.image1, style: "width: 150px; height: auto; padding: 5px; float: left;" %>
    <%= image_tag @room.image2, style: "width: 150px; height: auto; padding: 5px; float: left;" %>
    <%= image_tag @room.image3, style: "width: 150px; height: auto; padding: 5px; float: left;" %>


</div>


</div>
<div class="button-container">

<%= link_to  edit_room_path(@room) do %>
<div class="default-button">Edit</div>
<%end%>

<%= link_to  @room, method: :delete, data: { confirm: 'Are you sure?' } do %>
<div class="default-button">Delete</div>
<%end%>
</div>
</div>
</div>

<%= render 'bookings/form', booking: @booking, room: @room %>